[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    tests/.*/snapshots/.*
  | \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
multi_line_output = 3
line_length = 120
combine_as_imports = true
force_grid_wrap = 0
skip_glob = '*/snapshots/*'
include_trailing_comma = true
balanced_wrapping = true
combine_star = true
intend = 4
lines_between_types = true
order_by_type = true
use_parentheses = true
