[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = 'tests/.*/snapshots/.*'

[tool.isort]
multi_line_output = 3
line_length = 120
combine_as_imports = true
force_grid_wrap = 0
skip_glob = '*/snapshots/*'
include_trailing_comma = true

